<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bintang 5 pelayanan perqara</name>
   <tag></tag>
   <elementGuidId>2cd6faed-2cdb-4e67-bfce-ea9e0b271214</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wrap-ratingApp > div.py-2.flex.justify-center > div > div.flex.flex-row.gap-2 > div:nth-of-type(5) > img.w-6.h-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrap-ratingApp']/div/div/div/div[5]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a8c0c9da-97a3-4ca2-a3e5-47ddd1664e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-6 h-6</value>
      <webElementGuid>a1e7a0e6-08a6-4f38-aa61-0198eeb2b84c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/image/yellow-star.png</value>
      <webElementGuid>f0bc6ab8-3390-4ca7-a1fa-78d292dbfb26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>yellow-star</value>
      <webElementGuid>5a68eba7-4d2c-436c-9147-e10fce5a6653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrap-ratingApp&quot;)/div[@class=&quot;py-2 flex justify-center&quot;]/div[1]/div[@class=&quot;flex flex-row gap-2&quot;]/div[5]/img[@class=&quot;w-6 h-6&quot;]</value>
      <webElementGuid>8d39ba41-ded0-46c2-8c1f-861a8425a29b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrap-ratingApp']/div/div/div/div[5]/img</value>
      <webElementGuid>9d590074-a474-4f99-9e56-f813ce7e7796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='yellow-star'])[10]</value>
      <webElementGuid>aa895e68-a85a-474d-84f8-2ad6269c3c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div[5]/img</value>
      <webElementGuid>e75ea2f1-6476-4be2-a6d6-786ab66de0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/image/yellow-star.png' and @alt = 'yellow-star']</value>
      <webElementGuid>b4e35e0b-0857-4402-8f64-745ad061fbd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
