<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tidak</name>
   <tag></tag>
   <elementGuidId>de1c4474-cd8f-428a-9a1e-9d6eb9960955</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__nuxt']/div/main/div[2]/section/div/div/div/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4a96d920-54ac-4123-bd17-c7c774667a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-blue-2 mt-8 text-blue-2 w-36 text-sm py-2.5 rounded-lg antialiased</value>
      <webElementGuid>13ecb549-2e62-4b3a-8db0-13134c5696a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tidak </value>
      <webElementGuid>07dfb8b8-68aa-4bf9-9acd-6cbd436bb20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[@class=&quot;bg-cultured font-dm-sans min-h-screen&quot;]/main[1]/div[@class=&quot;bg-cultured&quot;]/section[1]/div[1]/div[@class=&quot;grid place-items-center fixed overflow-auto top-0 left-0 h-full w-full bg-black bg-opacity-50 z-30 xl:px-36 z-50&quot;]/div[@class=&quot;bg-white md:w-tablet rounded-lg shadow-lg px-8 py-8&quot;]/div[@class=&quot;flex gap-2 justify-center&quot;]/div[1]/button[@class=&quot;border border-blue-2 mt-8 text-blue-2 w-36 text-sm py-2.5 rounded-lg antialiased&quot;]</value>
      <webElementGuid>aa638495-1d49-4cb9-9259-a5b3e0ad593d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/main/div[2]/section/div/div/div/div[2]/div/button</value>
      <webElementGuid>5c5d486d-db16-4b27-8d64-9ec208e1650e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[2]/following::button[1]</value>
      <webElementGuid>0a3de3f2-fa94-427f-945d-be2727ef1503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artikel Hukum'])[2]/following::button[1]</value>
      <webElementGuid>fe62680b-0f2e-4a20-902d-65e9d160e317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya, Akhiri'])[1]/preceding::button[1]</value>
      <webElementGuid>596aee7a-e1ab-4a42-bacc-6522659d12d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Noel, S.H'])[1]/preceding::button[3]</value>
      <webElementGuid>477d623a-72a7-4862-b0c4-a27970343e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tidak']/parent::*</value>
      <webElementGuid>b2b4ddb8-6f92-4b48-97b3-a63cbf50b010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>c7bb78a5-9d56-4863-b8ab-e9ea8259e0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Tidak ' or . = ' Tidak ')]</value>
      <webElementGuid>c4f7a0f6-abd1-4dfc-af89-29ee332503f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
