<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>review</name>
   <tag></tag>
   <elementGuidId>bb8a08f6-a640-491b-9059-d809b0586382</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dudukPerkara-form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='dudukPerkara-form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>03d13950-55f4-4354-babf-e1038507595a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dudukPerkara-form</value>
      <webElementGuid>8fe0ed95-19c3-4fd0-8976-5c0858a48979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-2 border border-gray-200 bg-gray-50 focus:border-gray-200 rounded-lg p-2 w-full text-neutral-600 text-sm</value>
      <webElementGuid>44a06ac2-c24b-4c6e-a788-d09ff7ece82d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dudukPerkara-form</value>
      <webElementGuid>61fdb669-d6c3-4fb0-b298-d667977ec665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a6b6c663-8361-4506-829f-7a9b09d24815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dudukPerkara-form&quot;)</value>
      <webElementGuid>8cdc80de-4b57-4bd2-9325-2cb0cdc96f30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='dudukPerkara-form']</value>
      <webElementGuid>d60139dd-3d6d-4977-83b3-e719e1b3bb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrap-contentRating']/div[6]/textarea</value>
      <webElementGuid>d0e3afe2-7d6a-4dc7-b3c7-09c35484735e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>ae77f424-aab4-4954-b68b-ce5e6985ac78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'dudukPerkara-form' and @name = 'dudukPerkara-form']</value>
      <webElementGuid>b8fb369c-85cc-4abc-95c9-c60ecabb087c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
