<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tombol kirim</name>
   <tag></tag>
   <elementGuidId>588dbf88-f54e-4620-a01c-d116689d7593</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.text-white.text-base.w-full.text-center.py-2.mb-4.rounded-lg.bg-blue-2.border-blue-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__nuxt']/div/main/div[2]/section/div/div/div/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b49bf531-e502-4c2e-bd77-6a96be4f903e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white text-base w-full text-center py-2 mb-4 rounded-lg bg-blue-2 border-blue-2</value>
      <webElementGuid>64faea58-7729-477e-9dbe-875b44572c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Kirim </value>
      <webElementGuid>9289c502-1140-4f08-bc42-57f5275904ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[@class=&quot;bg-cultured font-dm-sans min-h-screen&quot;]/main[1]/div[@class=&quot;bg-cultured&quot;]/section[1]/div[1]/div[@class=&quot;grid place-items-center fixed top-0 left-0 w-full h-full bg-black/50 z-50 xl:px-36 z-50&quot;]/div[@class=&quot;bg-white shadow-lg absolute overflow-auto md:max-w-[441px] max-h-[95%] scrollbar p-4 sm:p-5 md:p-7 bottom-0 xs:bottom-auto rounded-b-none xs:rounded-b-2xl rounded-t-2xl&quot;]/div[@class=&quot;sticky bottom-0 bg-white shadow-2xl shadow-slate-300 md:rounded-b-lg lg:shadow-none lg:bg-&quot;]/div[@class=&quot;p-4 md:px-8&quot;]/button[@class=&quot;text-white text-base w-full text-center py-2 mb-4 rounded-lg bg-blue-2 border-blue-2&quot;]</value>
      <webElementGuid>a610e88e-a00d-4231-b413-610888ae3aa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/main/div[2]/section/div/div/div/div[2]/div/button</value>
      <webElementGuid>63f9eccc-016c-468b-952d-6002f637fb83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[2]/following::button[1]</value>
      <webElementGuid>9023967b-e654-4abf-a920-d56aecd20d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artikel Hukum'])[2]/following::button[1]</value>
      <webElementGuid>a665be0e-6fa7-4806-9ccb-6d47a0f72b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Noel, S.H'])[2]/preceding::button[2]</value>
      <webElementGuid>16e7565a-0d31-4f83-8f2e-ab2f1c746f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Masalah'])[1]/preceding::button[2]</value>
      <webElementGuid>7ebea173-4152-49f1-b050-38249a4506ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kirim']/parent::*</value>
      <webElementGuid>82067574-002c-49ed-a99c-ca446f761e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>6a114a46-01ad-4345-8f91-beaa200a6c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Kirim ' or . = ' Kirim ')]</value>
      <webElementGuid>3ac4c6f2-df61-47b6-888d-671a7489a606</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
