<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kata sandi advokat</name>
   <tag></tag>
   <elementGuidId>90673fc6-56ea-4411-8bfc-8079a578809e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4749dbdb-c2be-4082-989d-f30786248a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>12345dcd-f73a-45f6-b571-2dcb6e8eefab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>******</value>
      <webElementGuid>ed4ae896-4ded-45bb-9280-940318cb5fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-none w-full flex-1 rounded-lg focus:ring-2</value>
      <webElementGuid>67fc380c-4adf-436a-ae26-c66bfc8b34bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[@class=&quot;bg-cultured font-dm-sans min-h-screen&quot;]/div[@class=&quot;relative bg-[#10172A] min-h-screen&quot;]/div[@class=&quot;relative w-full md:w-[632px] mx-auto pt-[169px] md:pt-[241px] md:px-0 px-4&quot;]/div[@class=&quot;mt-8 sm:mx-[90px]&quot;]/div[@class=&quot;bg-white rounded-2xl sm:p-8 p-4 sm:h-[600px] h-[500px] overflow-hidden&quot;]/div[@class=&quot;flex flex-col justify-between h-full&quot;]/div[@class=&quot;flex flex-col sm:gap-6 gap-4 flex-1&quot;]/div[2]/div[1]/div[@class=&quot;relative w-full border rounded-lg text-black border-gray-300&quot;]/input[@class=&quot;border-none w-full flex-1 rounded-lg focus:ring-2&quot;]</value>
      <webElementGuid>84289aff-0e59-4c17-9323-0d1fdb043e2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>2d9d336a-57d7-4334-a54b-1c279a084f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>3c452926-99ae-47ff-a280-fdc95a8af219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>e9cf6499-9682-422b-86f3-9cb0caa8475a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = '******']</value>
      <webElementGuid>f5b347d8-63c0-4e6d-a38f-6f7eded982cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
