<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>otp 5 advokat</name>
   <tag></tag>
   <elementGuidId>b22c0ffc-5ddb-4514-a56d-8f21b0786fda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ead2530e-60a7-440f-8f7c-ee28cd86b9df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>c1a69063-303f-470a-ac27-1eb6752a9b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-dm-sans</value>
      <webElementGuid>b17cf294-a783-429d-8bfb-d9a12c8f6518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f61f724a-4cd4-45c5-ab68-ad76732621f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>836f273c-91bc-470d-bad9-b00dbf7addce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9a31444c-6cd9-4dd5-abf9-dd74769bfe6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4&quot;)</value>
      <webElementGuid>d81fdb69-fc71-4c2f-b11c-0770d8a67b41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='4']</value>
      <webElementGuid>25d5043e-53ad-4b7d-ac6a-79aacb72fb21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='input_4']/input</value>
      <webElementGuid>3aee4d21-e638-40a8-b72b-8a36a3215bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>8c7749df-47b1-4ccb-addf-d38eb98350e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '4' and @type = 'text' and @placeholder = '0']</value>
      <webElementGuid>18a66da1-2fc2-4b91-8ef5-a0d39530cd7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
