<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>otp 4 advokat</name>
   <tag></tag>
   <elementGuidId>cb29c957-044c-4b63-acac-3c2cf267bfd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9e8c0fb-4d20-4b78-9fac-01be40c99802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>1fdb0f4a-34f9-41aa-a6c4-572c06b2d6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-dm-sans</value>
      <webElementGuid>3400f19d-80cf-4965-b552-64eeb301b3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>344eca97-8e0e-4bd0-869a-de0e4f3bf59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>befc1596-7172-42a9-95df-69ec1865c302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>80d9e92e-8033-4530-90ac-ccd2e2b04383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3&quot;)</value>
      <webElementGuid>ff7dd288-8c11-452a-a81d-dcd38e97b0fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='3']</value>
      <webElementGuid>e28e6d89-f4de-48ba-ab91-9045f66080ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='input_3']/input</value>
      <webElementGuid>bce7db5f-3e72-442c-aab0-58c3e2c776d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>9d5c9d7e-bbc4-4a3a-b68b-395d2ec8414c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '3' and @type = 'text' and @placeholder = '0']</value>
      <webElementGuid>8b622199-4eeb-4396-a3ee-b9df93fab3b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
