<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tombol login advokat on footer</name>
   <tag></tag>
   <elementGuidId>21741933-58ad-4e10-a2dc-3a53ca98f8ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;register-lawyer&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='register-lawyer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b1ab7796-d917-4bb2-8a21-a979a86be083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/image/registerLawyer-logo.png</value>
      <webElementGuid>a014556e-342d-4654-910f-ad1402741ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>register-lawyer</value>
      <webElementGuid>a5b9773d-7971-4b49-b8c9-972ac2ac241a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[@class=&quot;bg-cultured font-dm-sans min-h-screen&quot;]/main[1]/div[@class=&quot;bg-white -mt-16&quot;]/div[@class=&quot;w-full bg-gradient-to-r from-blue-1 to-blue-2&quot;]/div[@class=&quot;flex justify-center max-w-[1280px] p-4 xl:px-40 mx-auto&quot;]/div[@class=&quot;max-w-mobile md:max-w-tablet lg:max-w-full&quot;]/div[@class=&quot;lg:flex w-full&quot;]/div[@class=&quot;mt-8 flex w-full text-white gap-3 lg:pl-32&quot;]/div[@class=&quot;font-dm-sans antialiased ml-2&quot;]/div[@class=&quot;mt-2 hidden lg:block&quot;]/div[@class=&quot;mt-8&quot;]/div[@class=&quot;flex justify-center lg:justify-start&quot;]/a[@class=&quot;mt-2 w-1/2&quot;]/img[1]</value>
      <webElementGuid>a723bb93-443c-44c7-846e-3f1bbe4d660d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/main/div[2]/div[10]/div/div/div/div[2]/div[2]/div/div[2]/div/a/img</value>
      <webElementGuid>55a22077-516d-4d4e-9168-897b80b9ee85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='register-lawyer']</value>
      <webElementGuid>1ef6e2f1-0d82-4af6-a0d2-a3ac327a2fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/a/img</value>
      <webElementGuid>e53ab693-283d-4027-9a13-fb453950e3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/image/registerLawyer-logo.png' and @alt = 'register-lawyer']</value>
      <webElementGuid>790fc917-409e-4ca0-bc69-73219d9fbf19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
