<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>landing page-login-dropdown akun</name>
   <tag></tag>
   <elementGuidId>33a5cd90-7b8d-4ebf-9a10-4119ce32afb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4f05d3ca-0b59-460e-a138-8d6c4932e062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2 sm:px-3 py-1 flex items-center gap-2 bg-white border border-blue-5 rounded-lg cursor-pointer</value>
      <webElementGuid>8679e7e0-a55c-4d18-a0f5-23445c0e58f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hertina Nengsih</value>
      <webElementGuid>6953ad32-13ee-46e2-a7f9-08038272e46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[@class=&quot;bg-cultured font-dm-sans min-h-screen&quot;]/main[1]/div[@class=&quot;relative w-full py-2.5 px-4 h-16 transition-all duration-300 ease-in-out sticky top-0 z-50 bg-transparent top-16&quot;]/div[@class=&quot;max-w-[1280px] mx-auto xl:px-40&quot;]/div[@class=&quot;flex justify-between gap-2 items-center&quot;]/div[@class=&quot;flex items-center&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;px-2 sm:px-3 py-1 flex items-center gap-2 bg-white border border-blue-5 rounded-lg cursor-pointer&quot;]</value>
      <webElementGuid>d3a9aa89-e91e-49f3-abf9-2b08a8bfdbd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/main/div/div/div/div[2]/div/div</value>
      <webElementGuid>200dea0c-40af-40cb-988a-f55e41c9f429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[1]/following::div[3]</value>
      <webElementGuid>0a3710e8-e61b-484b-9c12-5da8c075ecbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artikel Hukum'])[1]/following::div[3]</value>
      <webElementGuid>fe696a29-f783-48ac-8ac0-d1fbab748045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layanan Hukum'])[2]/preceding::div[2]</value>
      <webElementGuid>5048399d-39bd-4ccf-8146-fa6a537c12cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div</value>
      <webElementGuid>352bf06a-0109-44a9-a504-3c7804bf2a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hertina Nengsih' or . = 'Hertina Nengsih')]</value>
      <webElementGuid>481791ce-6e3c-43d4-8e7b-6383b05e9909</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
