<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>landing page-close banner</name>
   <tag></tag>
   <elementGuidId>9c9e9b7c-a099-4a9c-89e6-362fa8b0a432</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[1]/following::*[name()='svg'][9] | (.//*[normalize-space(text()) and normalize-space(.)='Syarat dan Ketentuan'])[1]/following::*[name()='svg'][9]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;__nuxt&quot;)/div[@class=&quot;bg-cultured font-dm-sans min-h-screen&quot;]/main[1]/div[@class=&quot;bg-white font-lexend -mt-16&quot;]/div[@class=&quot;fixed inset-0 bg-black/50 grid place-items-center z-50&quot;]/div[@class=&quot;px-4&quot;]/div[@class=&quot;flex items-center justify-center mt-3 cursor-pointer&quot;]/svg[1][count(. | //*[@xmlns = 'http://www.w3.org/2000/svg']) = count(//*[@xmlns = 'http://www.w3.org/2000/svg'])]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.items-center.justify-center.mt-3.cursor-pointer > svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>215c40df-80bf-4683-ab0d-54ffe0383e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>3690a1a9-b174-43ad-a101-216e8a211cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>d1cae46f-2ce9-431c-aca6-9c17a4696eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>c09932bf-e338-4546-a11d-d570b176de3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>212efe99-dfc6-4154-b4a6-89ab3b8ee9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>941bf518-d746-4175-a8b2-8896149652f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[@class=&quot;bg-cultured font-dm-sans min-h-screen&quot;]/main[1]/div[@class=&quot;bg-white font-lexend -mt-16&quot;]/div[@class=&quot;fixed inset-0 bg-black/50 grid place-items-center z-50&quot;]/div[@class=&quot;px-4&quot;]/div[@class=&quot;flex items-center justify-center mt-3 cursor-pointer&quot;]/svg[1]</value>
      <webElementGuid>cbee6e27-b23c-4a86-8278-309555dedb99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[1]/following::*[name()='svg'][9]</value>
      <webElementGuid>b4d85917-652c-4a55-84ba-13d6c30cc417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat dan Ketentuan'])[1]/following::*[name()='svg'][9]</value>
      <webElementGuid>82b27628-4ba3-42ef-a871-668ca765ef8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
