<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DANA</name>
   <tag></tag>
   <elementGuidId>0b5ea35e-e075-45a0-af0b-cfb4d04190b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:rh:']/div/ul/li/button/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a560e5f0-aded-4e5d-a42b-1393378206e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-center border-.5 border-xen-gray-300 sm:rounded ring-primary transition px-3 h-10 sm:px-10 sm:h-24 w-20 sm:w-full space-y-1.5 bg-white group-hover:border-primary sm:group-focus:ring-2</value>
      <webElementGuid>0898ee90-6a6e-4a95-bfda-a4b52deaa394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rh:&quot;)/div[@class=&quot;px-10 pt-0 pb-3 sm:px-2 sm:py-3 flex justify-center&quot;]/ul[@class=&quot;w-full flex flex-wrap sm:-mx-2&quot;]/li[@class=&quot;sm:px-2 w-full sm:w-1/3 sm:pb-4&quot;]/button[@class=&quot;w-full group p-1.5 sm:p-0 flex items-center space-x-3 text-left focus:bg-xen-gray-300 transition-colors outline-none&quot;]/div[@class=&quot;flex items-center justify-center border-.5 border-xen-gray-300 sm:rounded ring-primary transition px-3 h-10 sm:px-10 sm:h-24 w-20 sm:w-full space-y-1.5 bg-white group-hover:border-primary sm:group-focus:ring-2&quot;]</value>
      <webElementGuid>94a9c616-d6b1-451c-ba36-f5a4c7121e27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rh:']/div/ul/li/button/div</value>
      <webElementGuid>2aed1ecf-238a-4dbf-9baf-3b98dcd349fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-Wallet'])[1]/following::div[4]</value>
      <webElementGuid>adeb62da-d8a0-4d2c-a495-1a08dfe3cf21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Method'])[1]/following::div[6]</value>
      <webElementGuid>a4c373d1-525f-44b2-bba7-eb64b49b1987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DANA'])[1]/preceding::div[1]</value>
      <webElementGuid>6797953e-6aec-4db2-a9f2-888bb289d13b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ShopeePay / SPayLater'])[1]/preceding::div[2]</value>
      <webElementGuid>a3693e09-04bc-4c4d-b0f8-0c18083442cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/button/div</value>
      <webElementGuid>82283043-0cba-4467-bd11-4cf7adc8bdb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
