<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OVO</name>
   <tag></tag>
   <elementGuidId>bb2e5e5e-10ea-4374-9703-dd77565bad37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:rh:']/div/ul/li[3]/button/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>94d6fbae-5efd-4f25-b3d5-22c86485b3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-center border-.5 border-xen-gray-300 sm:rounded ring-primary transition px-3 h-10 sm:px-10 sm:h-24 w-20 sm:w-full space-y-1.5 bg-white group-hover:border-primary sm:group-focus:ring-2</value>
      <webElementGuid>d717bbb1-ad91-4360-93cc-9dd1465c025b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rh:&quot;)/div[@class=&quot;px-10 pt-0 pb-3 sm:px-2 sm:py-3 flex justify-center&quot;]/ul[@class=&quot;w-full flex flex-wrap sm:-mx-2&quot;]/li[@class=&quot;sm:px-2 w-full sm:w-1/3 sm:pb-4&quot;]/button[@class=&quot;w-full group p-1.5 sm:p-0 flex items-center space-x-3 text-left focus:bg-xen-gray-300 transition-colors outline-none&quot;]/div[@class=&quot;flex items-center justify-center border-.5 border-xen-gray-300 sm:rounded ring-primary transition px-3 h-10 sm:px-10 sm:h-24 w-20 sm:w-full space-y-1.5 bg-white group-hover:border-primary sm:group-focus:ring-2&quot;]</value>
      <webElementGuid>3ec999ff-13e9-4f20-a9c4-c25bb1f759e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rh:']/div/ul/li[3]/button/div</value>
      <webElementGuid>49f45ece-fea3-4566-a1f3-637082c01363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ShopeePay / SPayLater'])[1]/following::div[1]</value>
      <webElementGuid>84cd67d0-638f-41be-af48-ffb66e2a728a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DANA'])[1]/following::div[2]</value>
      <webElementGuid>60eab57f-152f-4ff6-ab22-cf2b3bd0ee21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OVO'])[1]/preceding::div[1]</value>
      <webElementGuid>65464827-5bcf-4286-997c-c40ed4a6d987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Powered by'])[1]/preceding::div[4]</value>
      <webElementGuid>78667800-44f6-44bc-8731-bc13e92b28f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/button/div</value>
      <webElementGuid>65468117-8dfe-4696-9640-1a63baf80e4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
