<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Shopeepay</name>
   <tag></tag>
   <elementGuidId>4e520aab-ee57-4b79-91af-c3eb1507ee75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:rh:']/div/ul/li[2]/button/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ec0cae4-aed8-4bef-9f3e-110c177b0682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-center border-.5 border-xen-gray-300 sm:rounded ring-primary transition px-3 h-10 sm:px-10 sm:h-24 w-20 sm:w-full space-y-1.5 bg-white group-hover:border-primary sm:group-focus:ring-2</value>
      <webElementGuid>769a490a-3a8e-4135-986b-09ab4473ccdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rh:&quot;)/div[@class=&quot;px-10 pt-0 pb-3 sm:px-2 sm:py-3 flex justify-center&quot;]/ul[@class=&quot;w-full flex flex-wrap sm:-mx-2&quot;]/li[@class=&quot;sm:px-2 w-full sm:w-1/3 sm:pb-4&quot;]/button[@class=&quot;w-full group p-1.5 sm:p-0 flex items-center space-x-3 text-left focus:bg-xen-gray-300 transition-colors outline-none&quot;]/div[@class=&quot;flex items-center justify-center border-.5 border-xen-gray-300 sm:rounded ring-primary transition px-3 h-10 sm:px-10 sm:h-24 w-20 sm:w-full space-y-1.5 bg-white group-hover:border-primary sm:group-focus:ring-2&quot;]</value>
      <webElementGuid>a05406cd-8b30-4729-aed1-7210e0d20bf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rh:']/div/ul/li[2]/button/div</value>
      <webElementGuid>2f73fd7e-3d73-4e6a-a169-b5ffca5f4e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DANA'])[1]/following::div[1]</value>
      <webElementGuid>fc2fb580-cafc-4ada-8bdf-13664d3ecb19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-Wallet'])[1]/following::div[5]</value>
      <webElementGuid>66a1f126-e568-499a-8f0f-09be2738ec90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ShopeePay / SPayLater'])[1]/preceding::div[1]</value>
      <webElementGuid>a6b3a8b5-4252-4426-96d7-a1c52ec40f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OVO'])[1]/preceding::div[2]</value>
      <webElementGuid>e08ef9e9-fba4-47a3-b7d8-bf2e5ac565d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button/div</value>
      <webElementGuid>ca99a177-b84a-4458-bee6-c1066974f9fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
