<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tombol_Click here to simulate your payment with OVO</name>
   <tag></tag>
   <elementGuidId>2cf4bac4-3c9d-45e8-b8f9-02cd43718a08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>643efe9d-fdcc-46db-8446-b715c3dec95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e9f0c398-6d0c-4dd3-8190-1c91a9335d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-0 text-white font-semibold text-base underline focus:outline-none</value>
      <webElementGuid>d9d29220-c820-4087-b567-72ec665c8a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>simulate-button</value>
      <webElementGuid>e3c647d9-14b9-496e-a843-855e24645df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click here to simulate your payment with OVO</value>
      <webElementGuid>99905f3f-e64e-41cf-b579-99b87fab444e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;simulation-bar-portal&quot;)/div[@class=&quot;bg-xen-red-500 text-center py-1.5 px-4&quot;]/button[@class=&quot;p-0 text-white font-semibold text-base underline focus:outline-none&quot;]</value>
      <webElementGuid>42db2558-4a44-448a-a970-f5225e5036bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>b307411f-e927-4d29-9d60-a83c559d2928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='simulation-bar-portal']/div/button</value>
      <webElementGuid>67e398ab-1437-40cd-910d-b1664193a5b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perqara'])[1]/preceding::button[1]</value>
      <webElementGuid>a9e99c71-31ce-48b9-87a2-22767f8904ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/preceding::button[1]</value>
      <webElementGuid>a24b8f7b-46cd-450a-a8f7-f3fa5ee7cf24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Click here to simulate your payment with OVO']/parent::*</value>
      <webElementGuid>222654f0-08bb-4b1f-a917-bc01e780cacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>b63bfc2d-2117-47a9-b494-1bb83c124bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Click here to simulate your payment with OVO' or . = 'Click here to simulate your payment with OVO')]</value>
      <webElementGuid>343d3ee7-4269-414e-ab66-ade71772586d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
