<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown E-wallet</name>
   <tag></tag>
   <elementGuidId>e92705c2-3937-4705-a48c-77848bec21df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='radix-:rg:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>97003c41-8c02-4846-a01e-514a0cebdfbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4d44b149-5866-44da-9ec1-9374f0567b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:rh:</value>
      <webElementGuid>3dbaf5b7-98db-441f-a6a0-6b5c910518ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9b8461da-348e-4a5c-9167-9107ee1b8b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>72d02ea1-89fb-47f3-bba2-720a0c85ab05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>vertical</value>
      <webElementGuid>e9b728de-f352-4de5-963e-391dc804f4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:rg:</value>
      <webElementGuid>2cdf72c2-c7c8-4e4b-b10a-a92131d568e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-4 flex flex-1 items-center justify-between [&amp;[data-state=open]>span>svg>path]:first:stroke-primary [&amp;[data-state=open]>span>svg>rect]:first:stroke-primary transition-all [&amp;[data-state=open]>svg]:rotate-180 [&amp;[data-state=open]>span>[data-role=preview]]:hidden</value>
      <webElementGuid>5e48fad1-6f34-4738-b683-7d4536c589b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>payment-channel-list-ewallet</value>
      <webElementGuid>f05b3945-7b1f-470a-85b4-1bf8136c5549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>E-Wallet</value>
      <webElementGuid>24002298-dc53-4dad-84e2-9106294d9032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rg:&quot;)</value>
      <webElementGuid>1a253052-2916-45bd-905f-8313b0fc6f21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='radix-:rg:']</value>
      <webElementGuid>594d3310-51c5-48cc-a75b-e1a43506d5d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div/section[2]/div/div/div/h3/button</value>
      <webElementGuid>f3410257-56a3-4c49-8217-98af95e28ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Method'])[1]/following::button[1]</value>
      <webElementGuid>d4fdc31a-d2cc-4c38-ad8d-a57a43105aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Summary'])[2]/following::button[1]</value>
      <webElementGuid>5347d3b3-12b5-4655-9d74-0345a81a8777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ShopeePay / SPayLater'])[1]/preceding::button[1]</value>
      <webElementGuid>c3ddd0ec-c18c-401d-92ce-f46744d145ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/button</value>
      <webElementGuid>1f8930f0-658e-4c3d-b9ac-9983d8b9ae1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'radix-:rg:' and (text() = 'E-Wallet' or . = 'E-Wallet')]</value>
      <webElementGuid>8e57600b-27d3-4539-8a78-8e335498e7c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
