<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>simulasikan pembayaran</name>
   <tag></tag>
   <elementGuidId>478200a5-3667-4f91-ba7b-aae9d72ee4e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='simulation-bar-portal']/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>37b382c5-a52e-4360-b424-4fb355b1c063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc7b138e-505e-4606-88f9-05cfc7a589b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-0 text-white font-semibold text-base underline focus:outline-none</value>
      <webElementGuid>6fb70730-1fc9-4866-9983-480076899faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>simulate-button</value>
      <webElementGuid>cb27853a-f1a6-4a06-8e31-eba24c02a55c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click here to simulate your payment with OVO</value>
      <webElementGuid>df2fa21d-532b-47c4-be5a-eea67ae7cd90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;simulation-bar-portal&quot;)/div[@class=&quot;bg-xen-red-500 text-center py-1.5 px-4&quot;]/button[@class=&quot;p-0 text-white font-semibold text-base underline focus:outline-none&quot;]</value>
      <webElementGuid>5d945c67-b9d6-442f-9c1a-c67e49295419</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>8cfb68a5-e2be-453f-8400-1cdf4e6a8b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='simulation-bar-portal']/div/button</value>
      <webElementGuid>ac750fc3-775e-4939-ac66-f4386779aa54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perqara'])[1]/preceding::button[1]</value>
      <webElementGuid>1014055a-1c32-4c24-a6d4-07f402c5f889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/preceding::button[1]</value>
      <webElementGuid>344a219c-da15-4930-9eb6-e3d4eabc52a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Click here to simulate your payment with OVO']/parent::*</value>
      <webElementGuid>9342705c-da6f-422c-a67b-c4e1a89e4ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>7703c860-7e08-46c1-92e9-0f0da9ea9695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Click here to simulate your payment with OVO' or . = 'Click here to simulate your payment with OVO')]</value>
      <webElementGuid>31776ef6-77ba-4f02-8b84-31b2d92e99b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
