<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>jenis klamin laki laki</name>
   <tag></tag>
   <elementGuidId>d2a7d77a-806c-40b9-bbfc-d9bd21437bc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Laki - Laki']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.border.rounded-tl-lg.rounded-bl-lg.w-full.px-4.text-center.text-sm.py-3.border-gray-300.text-gray-500.font-normal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3345bce-6323-4331-8b61-72b090ecdcc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a77c39d0-d331-43e0-a627-767386b068b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border rounded-tl-lg rounded-bl-lg w-full px-4 text-center text-sm py-3 border-gray-300 text-gray-500 font-normal</value>
      <webElementGuid>292e2c34-e05c-410e-8a90-ed47968e5311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Laki - Laki</value>
      <webElementGuid>35df6592-94ff-44c7-8ffa-96f4ac216185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-register&quot;)/div[@class=&quot;space-y-4&quot;]/div[@class=&quot;space-y-2&quot;]/div[1]/div[@class=&quot;flex w-full&quot;]/input[@class=&quot;border rounded-tl-lg rounded-bl-lg w-full px-4 text-center text-sm py-3 border-gray-300 text-gray-500 font-normal&quot;]</value>
      <webElementGuid>37299ef1-b704-4641-b2f7-c62c58cdb936</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Laki - Laki']</value>
      <webElementGuid>08752731-27ce-49b3-a3d2-1f7d0c2e7ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-register']/div/div[8]/div/div/input</value>
      <webElementGuid>171d425c-b22a-4f5e-959e-c7e678f1809a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>61dad39d-d374-4c4b-9ea2-5a2cc31f60f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>27c80421-cdcb-4e3d-b220-d549797cd2e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
