<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>jenis klamin perempuan</name>
   <tag></tag>
   <elementGuidId>a024a833-9a2b-4d39-9a4c-cbabb07f1dda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Perempuan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.border.rounded-tr-lg.rounded-br-lg.w-full.px-4.text-center.text-sm.py-3.border-gray-300.text-gray-500.font-normal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35e8f1b7-2af7-40ba-9c81-09249fbf8aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6c85424-e757-49ae-9017-5cc9007ceb5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border rounded-tr-lg rounded-br-lg w-full px-4 text-center text-sm py-3 border-gray-300 text-gray-500 font-normal</value>
      <webElementGuid>7e0e6c1f-f23d-4266-94b3-1be4d081694e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Perempuan</value>
      <webElementGuid>3fe95786-47c4-4a8b-8808-90606e8459d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-register&quot;)/div[@class=&quot;space-y-4&quot;]/div[@class=&quot;space-y-2&quot;]/div[1]/div[@class=&quot;flex w-full&quot;]/input[@class=&quot;border rounded-tr-lg rounded-br-lg w-full px-4 text-center text-sm py-3 border-gray-300 text-gray-500 font-normal&quot;]</value>
      <webElementGuid>73ffffdd-e250-4989-b326-53023af9daab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Perempuan']</value>
      <webElementGuid>d286dd8a-9d78-4f58-8c7b-952748521d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-register']/div/div[8]/div/div/input[2]</value>
      <webElementGuid>a5cca7e7-6486-4f2d-bc16-abfd284314c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>48217827-2334-4f93-b141-91d3a0d206b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>3fbbd47d-8f3c-4d8c-a9cb-0a1d7bd0c2e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
