<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nama lengkap</name>
   <tag></tag>
   <elementGuidId>be7246da-c851-46aa-9261-d7b25c3bc8f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-register']/div/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.border.rounded-lg.text-black.border-gray-300.w-full</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07d2aadd-2b91-45fc-9d62-e4a82ca8f72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>834f8dd0-723e-4cbc-9648-38e413ca2166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border rounded-lg text-black border-gray-300 w-full</value>
      <webElementGuid>12d8baae-0f02-4073-84a4-7be7277084c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tuliskan nama lengkap Anda</value>
      <webElementGuid>84db4a08-1078-476f-a00c-9d09795bab4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-register&quot;)/div[@class=&quot;space-y-4&quot;]/div[@class=&quot;space-y-2&quot;]/div[1]/input[@class=&quot;border rounded-lg text-black border-gray-300 w-full&quot;]</value>
      <webElementGuid>32bee98f-45bc-49df-bc8e-78e4396d84b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>f35b0b8e-61ba-4c19-bde2-25fff2dd9c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-register']/div/div/div/input</value>
      <webElementGuid>96a85dce-d437-49e4-928a-3903e53a4072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9bfc7062-242e-4bc3-abd4-0de41889ef0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Tuliskan nama lengkap Anda']</value>
      <webElementGuid>f49a62f5-ba3e-492d-9859-ed240c90993b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
