<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tombol advokat perqara register</name>
   <tag></tag>
   <elementGuidId>d604de0f-dc57-4e85-a977-84776cc87a90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-register']/div/div[4]/div[7]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.w-full.cursor-pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2bc3775f-2045-4ccf-bd5f-f80a95c9404c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full cursor-pointer</value>
      <webElementGuid>cbc8acee-073c-4ced-a264-ea18075ffbbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/image/lawyer/login/banner-login-advokat.png</value>
      <webElementGuid>a728ced0-0dc5-4278-a987-4ebeced59cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>banner-advokat</value>
      <webElementGuid>70d3ddd5-a68c-40eb-8ccd-91f8d42420a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-register&quot;)/div[1]/div[4]/div[@class=&quot;mt-4 flex justify-center&quot;]/div[@class=&quot;px-6 w-full md:w-full&quot;]/a[1]/img[@class=&quot;w-full cursor-pointer&quot;]</value>
      <webElementGuid>afec071b-8e65-40fc-af8a-390b74cc90d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-register']/div/div[4]/div[7]/div/a/img</value>
      <webElementGuid>0521926a-3f4d-4b17-b3da-1e947b484496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='banner-advokat']</value>
      <webElementGuid>22c6da62-28ab-4bcc-aa8d-498b3ac8f296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>2ed05719-3932-4feb-a28a-9f0a681734e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/image/lawyer/login/banner-login-advokat.png' and @alt = 'banner-advokat']</value>
      <webElementGuid>53a8e6a9-fd36-404a-8b0b-daf9742daf9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
