<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field Cari Advokat</name>
   <tag></tag>
   <elementGuidId>0baba468-330d-4bb2-8f9e-5995ddb3e83a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#default-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'default-search' and @type = 'search' and @placeholder = 'Cari Nama Advokat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2613dcd-2d58-4601-808c-0cfa9fe12e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>default-search</value>
      <webElementGuid>07913562-7dc5-4a26-b7fc-5ce5e577a394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>426c929a-00eb-4149-8afc-503583e700c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full py-3 pl-3 pr-10 text-base text-black border border-[#E7ECF0] rounded-lg bg-white focus:ring-blue-500 focus:border-blue-500 z-50 placeholder:text-[#9B9B9B] placeholder:text-xs md:placeholder:text-base</value>
      <webElementGuid>df7d8feb-f1ae-4015-8c98-eaf98b5f3773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Nama Advokat</value>
      <webElementGuid>cb87f588-6de4-45fc-9db0-e4e53b9238fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;default-search&quot;)</value>
      <webElementGuid>4cb6dbec-f3c3-46a2-a1fb-216cff1766f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='default-search']</value>
      <webElementGuid>4af7a6e8-fff8-46b8-8b1c-6525fe6984fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrap-inputSearching']/div/div/input</value>
      <webElementGuid>87687341-e6bf-4d8e-93e6-1a0b27cb9573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2c05eaee-af8c-477f-b44a-d918a9309cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'default-search' and @type = 'search' and @placeholder = 'Cari Nama Advokat']</value>
      <webElementGuid>d66fef6c-8901-4b44-a211-834648f6b6f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
