<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tombol Konsultasi</name>
   <tag></tag>
   <elementGuidId>895d0419-6872-4750-b3fd-ca8c9244fdc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[(text() = 'Konsultasi' or . = 'Konsultasi')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f62972a-da03-4f42-8e12-c2cd77fd5d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-medium px-4 py-2.5 md:px-6 md:py-3 md:w-32 rounded-md md:rounded-lg text-xs md:text-base bg-blue-2 text-white</value>
      <webElementGuid>c5df68f6-8e3d-452d-989c-9241103a167a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Konsultasi</value>
      <webElementGuid>494eceda-814b-4cb7-857e-f59bbb58244e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[@class=&quot;bg-cultured font-dm-sans min-h-screen&quot;]/main[1]/div[@class=&quot;bg-[#F6F9FD]&quot;]/div[@class=&quot;container max-w-[1280px] mx-auto xl:p-0 xl:px-40 h-full 2xl:h-auto relative&quot;]/div[@class=&quot;lg:grid lg:grid-cols-3 lg:gap-x-6 px-4&quot;]/div[@class=&quot;lg:col-span-2&quot;]/div[1]/div[@class=&quot;mb-4&quot;]/div[1]/div[@class=&quot;cursor-pointer mb-3&quot;]/div[@class=&quot;relative bg-white rounded-lg min-w-[328px] max-h-[239px] overflow-hidden border border-[#E7ECF0]&quot;]/div[@class=&quot;relative md:py-3 py-2&quot;]/div[@class=&quot;flex justify-between items-center gap-1 md:px-3 px-2&quot;]/button[@class=&quot;font-medium px-4 py-2.5 md:px-6 md:py-3 md:w-32 rounded-md md:rounded-lg text-xs md:text-base bg-blue-2 text-white&quot;]</value>
      <webElementGuid>7cc29d2f-487a-42e3-9812-54602749bf4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/main/div[2]/div[4]/div[3]/div[2]/div/div/div/div/div/div/div[4]/button</value>
      <webElementGuid>ab784dbe-0929-48f1-83ed-d52d8d3b25f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[1]/following::button[1]</value>
      <webElementGuid>38c7572d-5c2c-4709-9b75-d72ca6d5660c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perkawinan &amp; Perceraian'])[2]/following::button[1]</value>
      <webElementGuid>256dc347-0171-45c0-8600-889dc8576e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pro bono'])[1]/preceding::button[1]</value>
      <webElementGuid>457ecc52-1799-412d-b541-cc6b898ecab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tampilkan Lebih Banyak'])[1]/preceding::button[3]</value>
      <webElementGuid>79b6e855-2992-43bd-a170-93d6f7f98887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Konsultasi']/parent::*</value>
      <webElementGuid>4d254d86-7124-4a57-92bb-ee27d2935c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>d3541f6b-109b-430c-9e6d-8a65331707c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Konsultasi' or . = 'Konsultasi')]</value>
      <webElementGuid>15fc00a5-d30f-4707-b645-826b0b1ac0e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
