<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modal Pembayaran Berhasil</name>
   <tag></tag>
   <elementGuidId>c6e81742-37f4-4746-b89a-87cf81a51217</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__nuxt']/div/main/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.flex-col.items-center.text-center.gap-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f446f695-1b51-4923-b47f-a0a2a52be803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-col items-center text-center gap-4</value>
      <webElementGuid>429a0e75-7435-4deb-8af4-63e45072eeec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pembayaran Berhasil  Terimakasih kami telah menerima pembayaran Anda, konsultasi akan dimulai sebentar lagi </value>
      <webElementGuid>b6294aff-fdd0-45f4-8bbc-3b022bcfe23a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[@class=&quot;bg-cultured font-dm-sans min-h-screen&quot;]/main[1]/div[2]/div[@class=&quot;grid place-items-center fixed top-0 left-0 w-full h-full bg-black/50 z-50 xl:px-36&quot;]/div[@class=&quot;bg-white shadow-lg absolute overflow-auto w-full xs:w-[95%] md:w-[500px] max-h-[95%] scrollbar p-4 sm:p-5 md:p-7 bottom-0 xs:bottom-auto rounded-b-none xs:rounded-b-2xl rounded-t-2xl&quot;]/div[@class=&quot;flex flex-col items-center text-center gap-4&quot;]</value>
      <webElementGuid>27e55a68-88ed-48af-badf-baab2cb0ae04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/main/div[2]/div/div/div</value>
      <webElementGuid>5f8dabbd-6eb7-40a7-ba3c-814f09d1ddf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[2]/following::div[6]</value>
      <webElementGuid>bf8e1038-22f8-4621-a0b8-03981872a01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artikel Hukum'])[2]/following::div[6]</value>
      <webElementGuid>310917d9-0dcf-4ff3-840f-d397a2bdf68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selesaikan Pembayaran'])[1]/preceding::div[1]</value>
      <webElementGuid>87df8dbf-5b63-4cb3-9f75-086be6bedff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>f731b05c-f667-44fe-b791-cd996a342052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Pembayaran Berhasil  Terimakasih kami telah menerima pembayaran Anda, konsultasi akan dimulai sebentar lagi ' or . = ' Pembayaran Berhasil  Terimakasih kami telah menerima pembayaran Anda, konsultasi akan dimulai sebentar lagi ')]</value>
      <webElementGuid>21ac554f-747f-4ee3-aba0-2d0438e4d97f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
