<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modal menunggu konfirmasi</name>
   <tag></tag>
   <elementGuidId>f56f1e7d-ff91-4f15-8d1d-e0b11237ebce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.bg-white.rounded-xl.px-20.py-8.flex.flex-col.gap-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__nuxt']/div/main/div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cc2dd09b-e3de-4586-8bf5-c1db5230427f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-white rounded-xl px-20 py-8 flex flex-col gap-6</value>
      <webElementGuid>be41d187-cb0e-4378-9358-5b7ea3486bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>01:52Noel, S.HAdvokat akan menjawab sebentar lagi</value>
      <webElementGuid>54bdc8a7-17b8-4b59-bea0-e84c023fd95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[@class=&quot;bg-cultured font-dm-sans min-h-screen&quot;]/main[1]/div[@class=&quot;max-w-[550px] mx-auto pt-10 md:px-0 px-4&quot;]/div[2]/div[@class=&quot;bg-white rounded-xl px-20 py-8 flex flex-col gap-6&quot;]</value>
      <webElementGuid>388d017d-3377-4a1d-9f41-a5daed10e594</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/main/div[2]/div[2]/div</value>
      <webElementGuid>e41b76e2-b058-4225-9d01-d97f216ca950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu Konfirmasi'])[1]/following::div[2]</value>
      <webElementGuid>68119bc8-826b-41ec-bc86-027686a2a46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[2]/following::div[6]</value>
      <webElementGuid>fb2171e6-bf2b-4a27-b09b-eb27c9e35f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>48a64b5a-0e6b-4951-a1b1-581ccdbd8a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '01:52Noel, S.HAdvokat akan menjawab sebentar lagi' or . = '01:52Noel, S.HAdvokat akan menjawab sebentar lagi')]</value>
      <webElementGuid>b565e8b4-57fa-4f29-b438-8b167e833627</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
