<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OVO</name>
   <tag></tag>
   <elementGuidId>71fd3c8d-1ce9-460a-a71d-344d384edb04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[3]/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5902f3ea-cec2-45bc-bcbe-432c9a9c944c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-center border-.5 border-xen-gray-300 sm:rounded ring-primary transition px-3 h-10 sm:px-10 sm:h-24 w-20 sm:w-full space-y-1.5 bg-white group-hover:border-primary sm:group-focus:ring-2</value>
      <webElementGuid>3bdf29e5-49ac-4826-b102-235221790c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rh:&quot;)/div[@class=&quot;px-10 pt-0 pb-3 sm:px-2 sm:py-3 flex justify-center&quot;]/ul[@class=&quot;w-full flex flex-wrap sm:-mx-2&quot;]/li[@class=&quot;sm:px-2 w-full sm:w-1/3 sm:pb-4&quot;]/button[@class=&quot;w-full group p-1.5 sm:p-0 flex items-center space-x-3 text-left focus:bg-xen-gray-300 transition-colors outline-none&quot;]/div[@class=&quot;flex items-center justify-center border-.5 border-xen-gray-300 sm:rounded ring-primary transition px-3 h-10 sm:px-10 sm:h-24 w-20 sm:w-full space-y-1.5 bg-white group-hover:border-primary sm:group-focus:ring-2&quot;]</value>
      <webElementGuid>7cf4c221-1098-4576-a9a8-f1e8c27c58ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rh:']/div/ul/li[3]/button/div</value>
      <webElementGuid>c723fd36-b5d7-428c-92e0-cb22ac2f3fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DANA'])[1]/following::div[1]</value>
      <webElementGuid>a3bde237-e6dd-4fd8-b095-f4744fcd37ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ShopeePay / SPayLater'])[1]/following::div[2]</value>
      <webElementGuid>fe9d7155-70d0-4c13-b29b-ce64ab038e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OVO'])[1]/preceding::div[1]</value>
      <webElementGuid>59e3b347-b416-4e57-b49b-94a0b3d1c85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Powered by'])[1]/preceding::div[4]</value>
      <webElementGuid>b17aa40a-c034-4464-9dfe-15dd6139637a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/button/div</value>
      <webElementGuid>bb79a1d9-af0c-41e3-86dd-4c8a7789c32b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
