<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tombol Click here to simulate your payment with OVO</name>
   <tag></tag>
   <elementGuidId>50ca734a-8dd9-47f3-bb7d-7457a40f97f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and (text() = 'Click here to simulate your payment with OVO' or . = 'Click here to simulate your payment with OVO')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>998303ee-06ae-4d8a-93d8-40daee1169d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9205243a-3fd9-4d5f-ac80-1ee46e41d8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-0 text-white font-semibold text-base underline focus:outline-none</value>
      <webElementGuid>b8e603ae-54aa-46b5-ac3b-85a46b482efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>simulate-button</value>
      <webElementGuid>925befcd-6640-4fd1-8838-aa7389437c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click here to simulate your payment with OVO</value>
      <webElementGuid>d7a90808-d8a8-4e80-8110-56aa15774794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;simulation-bar-portal&quot;)/div[@class=&quot;bg-xen-red-500 text-center py-1.5 px-4&quot;]/button[@class=&quot;p-0 text-white font-semibold text-base underline focus:outline-none&quot;]</value>
      <webElementGuid>9290f121-e3c5-40b8-bd0f-86e610263637</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>34d8aba2-be11-427a-80bd-fd7609366289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='simulation-bar-portal']/div/button</value>
      <webElementGuid>91cd9966-e5ac-476b-bc9a-153682fcf011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perqara'])[1]/preceding::button[1]</value>
      <webElementGuid>97a31c76-a843-4215-b064-146382fdce53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/preceding::button[1]</value>
      <webElementGuid>6839c1e4-137b-469c-9e34-87629d4dede1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Click here to simulate your payment with OVO']/parent::*</value>
      <webElementGuid>701a3a40-5f77-49e7-9363-a27937511ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>42c8c82e-306f-4447-ab15-36429e6ee1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Click here to simulate your payment with OVO' or . = 'Click here to simulate your payment with OVO')]</value>
      <webElementGuid>661c3164-c1e8-423c-a712-a29de2024a15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
